AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'public/system/**'
    - 'tmp/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false
